appname = "rlrs"

[datasets.example]
question_text_file = "examples/ques_text.txt"
question_knowledge_file = "examples/id_know.txt"
question_difficulty_file = "examples/id_difficulty.txt"
word_list = "examples/words.txt"
knowledge_list = "examples/know_list.txt"
record_file = "examples/records.txt"

[datasets.zhixue_small]
question_text_file = "data/zhixue_small/ques.txt"
question_knowledge_file = "data/zhixue_small/id_firstknow.txt"
question_difficulty_file = "data/zhixue_small/id_difficulty.txt"
word_list = "data/zhixue_small/words.txt"
knowledge_list = "data/zhixue_small/firstknow_list.txt"
record_file = "data/zhixue_small/records.txt"

[datasets.zhixue]
question_text_file = "data/zhixue/id_fea.tsv"
question_knowledge_file = "data/zhixue/id_firstknow.txt"
question_difficulty_file = "data/zhixue/id_difficulty.txt"
word_list = "data/zhixue/words.txt"
knowledge_list = "data/zhixue/firstknow_list.txt"
record_file = "data/zhixue/records.tsv"

[datasets.ustcoj]
question_text_file = "data/ustcoj/ques_text.tsv"
question_knowledge_file = "data/ustcoj/ques_knowledge.tsv"
question_difficulty_file = "data/ustcoj/ques_difficulty.tsv"
word_list = "data/ustcoj/words.txt"
knowledge_list = "data/ustcoj/know_list.txt"
record_file = "data/ustcoj/records.tsv"

[datasets.poj]
question_text_file = "data/poj/ques_text.tsv"
question_knowledge_file = "data/poj/ques_knowledge.tsv"
question_difficulty_file = "data/poj/ques_difficulty.tsv"
word_list = "data/poj/words.txt"
knowledge_list = "data/poj/know_list.txt"
record_file = "data/poj/records.tsv"
